---
- hosts: all
  tasks:
    
    - name: Change the hostname to sample-hostname
      ansible.windows.win_hostname:
      name: {{ servername }}
    register: res

    - name: Reboot
      ansible.windows.win_reboot:
      when: res.reboot_required
