---
- hosts: all
  gather_facts: false
  tasks:
    - name: Create Directory {{ dir }}
      ansible.windows.win_file:
        path: "{{ dir }}"
        state: directory
        
    - name: Copy Files
      ansible.windows.win_copy:
        src: "{{ file_src }}"
        dest: "{{ destination }}"
        remote_src: true
      become_method: runas
      become_flags: logon_type=new_credentials logon_flags=netcredentials_only
      vars:
        ansible_become: yes
        ansible_become_user: "{{ domain_user }}"
        ansible_become_pass: "{{ domain_pass }}"
