---
- hosts: all
  gather_facts: true
  tasks:
    - name: Create a group in a custom path
      microsoft.ad.group:
        name: "{{ ansible_hostname }}_LA"
        scope: universal
        path: "{{ domain_ou }}"
        domain_username: "{{ domain_user }}"
        domain_password: "{{ domain_password }}"
        domain_server: "{{ domain_server }}"
        state: present
