---
- hosts: all
  gather_facts: true
  tasks:
      
    - name: Generate Random Password
      ansible.windows.win_shell: |
        function Get-RandomPassword
        {
        [int32[]]$ArrayofAscii=26,97,26,65,10,48,15,33
        $Complexity=4
        $PasswordLength=(Get-Random -Minimum 12 -Maximum 25)
        $NewPassword=$NULL
        Foreach ($counter in 1..$PasswordLength) {
        $pickSet=(GET-Random $complexity)*2
        $NewPassword=$NewPassword+[char]((get-random $ArrayOfAscii[$pickset])+$ArrayOfAscii[$pickset+1])
        }
        Return $NewPassword
        }
        $comppassword = Get-RandomPassword
      register: complexpass

    - debug:
          var: complexpass
