---
- hosts: all
  gather_facts: false
  tasks:
    - name: Deny TS Connections Registry
      ansible.windows.win_regedit:
        path: HKLM:\System\CurrentControlSet\Control\Terminal Server
        name: fDenyTSConnections
        data: 0
        type: dword
        
    - name: Getting List of Interfaces under
      ansible.windows.win_reg_stat:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\NetBT\Parameters\Interfaces
      register: interfaces

    - name: Changing NetBiosOption Registry recursively under Interfaces
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\NetBT\Parameters\Interfaces\"{{ interfaces }}"
        name: NetBiosOptions
        data: 2
        type: dword
        
