---
- hosts: all
  gather_facts: false
  tasks:
    - name: Deny TS Connections Registry
      ansible.windows.win_regedit:
        path: HKLM:\System\CurrentControlSet\Control\Terminal Server
        name: fDenyTSConnections
        data: 0
        type: dword
