---
- hosts: all
  gather_facts: false
  tasks:
    - name: Deny TS Connections Registry
      ansible.windows.win_regedit:
        path: HKLM:\System\CurrentControlSet\Control\Terminal Server
        name: fDenyTSConnections
        data: 0
        type: dword
        
    - name: Getting List of Interfaces under
      ansible.windows.win_reg_stat:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\NetBT\Parameters\Interfaces
      register: interfaces

    - name: Changing NetBiosOption Registry recursively under Interfaces
      ansible.windows.win_regedit:
        path: 'HKLM:\SYSTEM\CurrentControlSet\Services\NetBT\Parameters\Interfaces\{{ item }}'
        name: NetBiosOptions
        data: 2
        type: dword
      loop: "{{ interfaces.sub_keys }}"

    - name: Set Time Zone to Mountain Standard Time (MST)
      community.windows.win_timezone:
        timezone: Mountain Standard Time
      tags: timezone

    #- name: Allowing RDP on Windows Firewall
    #  community.windows.win_firewall_rule:
    #    group: "@FirewallAPI.dll,-28752"
    #    enabled: yes
    #  tags: firewall

    - name: Firewall rule to allow RDP on TCP port 3389
      community.windows.win_firewall_rule:
        name: Remote Desktop
        localport: 3389
        action: allow
        direction: in
        protocol: tcp
        #profiles: private
        state: present
        enabled: yes
      tags: firewall

    - name: Firewall rule to allow ICMP v4 (ping)
      community.windows.win_firewall_rule:
        name: ICMP Allow incoming V4 echo request
        enabled: yes
        state: present
        #profiles: private
        action: allow
        direction: in
        protocol: icmpv4
      tage: icmp
      
    - name: Adding Windows Product Key
      ansible.windows.win_shell: |
        $key = "JCNG6-RXVCM-DK42M-6KG7W-6MWV3"
        $service = get-wmiObject -query "select * from SoftwareLicensingService"
        $service.InstallProductKey($key)
        $service.RefreshLicenseStatus()
      tags: winkey
